version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    env_file:
      - .env
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - $POSTGRES_PORT:5432